name: fvbnn
channels:
  - pytorch
  - pyg
  - dglteam
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.9.7
  - pytorch=1.10.0
  - tensorflow-base=2.6.2
  - pip
  - pip:
    - deepchem==2.5.0
    - sklearn==0.0
    - gpytorch==1.6.0
    - rdkit==2023.3.2
    - scipy==1.7.1
    - numpy==1.22.4
    - pandas==1.3.4
    - pytdc==0.3.4
    - requests==2.31.0
    - tensorflow==2.7.0
    - lightgbm==3.3.2
